.TH "LIPSIA" "1" "November 2010" "Erik Tuerke" ""
.SH "NAME"
lipsia \- Leipzig Image Processing and Statistical Inference Algorithms (LIPSIA)
.SH "DESCRIPTION"
\fBLipsia\fR is a software package for the data processing and evaluation of
functional magnetic resonance images.  It was developed over the course of
several years at the Max-Planck-Institute for Human Cognitive and Brain
Sciences in Leipzig, Germany.  The analysis of fMRI data comprises various
aspects including filtering, spatial transformation, statistical evaluation as
well as segmentation and visualization. All these aspects are covered by
\fBLipsia\fR. For the statistical evaluation, a number of well established and
peer-reviewed algorithms were implemented in \fBLipsia\fR that allow an
effcient and user-friendly processing of fMRI data sets. As the amount of data
that must be handled is enormous, an important aspect in the development
\fBLipsia\fR was the efficiency of the software implementation.
.PP
\fBLipsia\fR currently operates exclusively on data in the VISTA data format.
However, the package contains converters for medical image data in iBruker,
ANALYZE  and NIfTI format -- converting VISTA images into NIfTI files is also
supported.
.PP
\fBLipsia\fR documentation and online help is provided by the \fBlipsia-doc\fR
package, and is accessible through the `lipsia-help` command.
.PP
.SH "SEE ALSO"
The \fBLipsia\fR homepage at
.I http:/
/www.cbs.mpg.de/institute/software/lipsia
.SH "AUTHOR"
\fBFSL\fR was written by Gabi Lohmann, and many others.
.PP
This manual page was written by Michael Hanke <michael.hanke@gmail.com>,
for the Debian project (but may be used by others).
